discord:
  message_limit: 20

llm:
  model: "gpt-4o-mini"
  temperature: 1.45
  max_completion_tokens: 1600
  top_p: 0.993

image_model:
  model: "dall-e-3"
  size: "1024x1024"
  response_format: "b64_json"

variation_model:
  model: "stability-ai/stable-diffusion-3.5-large-turbo"
  cfg: 1
  steps: 6
  prompt_strength: 0.8
